#JS Node CircleCI 2.0 Config file
#
# Resource https://circleci.com/docs/2.0/language-javascript/ for more details
#

version: 2
jobs:
  build:
    docker:
      #Image Version 
      - image:  circleci/node:7.10

      #Service Dependencies
      #Image Resource https://circleci.com/docs/2.0/circleci-images/

    working_directory: ~/repo

    steps:
        - checkout

        # Download and cache dependencies
        - restore_cache:
            keys:
              - v1-dependencies-{{checksum"package.json}}
              # fallback to using the latest cache if no exact match is found
              - v1-dependencies-

        - run: yarn install

        - save_cache:
              path:
                -  node_modules
              key: v1-depenxencies-{{ checksum "package.json"}}
          
        #run test!
        -  run: yarn test

